---
title: "metafor"
author: "BBL"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
theme_set(theme_minimal())
```

# Setup

Read the google sheet data and reshape so that control values have their own columns:

```{r}
read_csv("rs/Variance and N - Water manipulations.csv", skip = 2,
         col_types = "ddcdcccdcccdddddddddddc") %>% #filter(Study_number==10526) %>% 
  select(-Notes) %>% 
  mutate(Manipulation = case_when(
    Percent_control < 100 ~ "Drought",
    Percent_control > 100 ~ "Irrigation",
    TRUE ~ "Control"
  )) ->
  dat

# Construct and control data frame
dat %>% 
  filter(Manipulation == "Control") %>% 
  select(-Record_number, -Author, -Manipulation, -Manipulation_level, -N, -SM_mean, -SM_sd)->
  dat_control
dat_control %>% 
  select(-starts_with("SD_"), -Percent_control) %>% 
  pivot_longer(cols = c(Rs_annual, Rh_annual, Rs_growingseason), 
               names_to = "depvar", values_to = "control") ->
  cont1
dat_control %>% 
  select(-Rs_annual, -Rh_annual, -Rs_growingseason, -Percent_control) %>% 
  pivot_longer(cols = c(SD_Rs_annual, SD_Rh_annual, SD_Rs_growingseason),
               names_to = "depvar", values_to = "SD_control") %>% 
  mutate(depvar = gsub("SD_", "", depvar)) ->
  cont2

cont1 %>% left_join(cont2) -> dat_control

# and manipulation data frame
dat %>% 
  filter(Manipulation != "Control") %>% 
  select(-starts_with("SD_")) %>% 
  pivot_longer(cols = c(Rs_annual, Rh_annual, Rs_growingseason), 
               names_to = "depvar", values_to = "manip") ->
  manip1
dat %>% 
  filter(Manipulation != "Control") %>% 
  select(-Rs_annual, -Rh_annual, -Rs_growingseason) %>% 
  pivot_longer(cols = c(SD_Rs_annual, SD_Rh_annual, SD_Rs_growingseason), 
               names_to = "depvar", values_to = "SD_manip") %>% 
  mutate(depvar = gsub("SD_", "", depvar)) ->
  manip2

manip1 %>% left_join(manip2) -> dat_manip

# ...and join with the manipulation data
dat_manip %>% 
  left_join(dat_control, 
            by = c("Study_number", "Study_midyear", "Ecosystem_type",
                   "Latitude", "Meas_method", "Soil_type", "Soil_drainage",
                   "Elevation", "depvar")) %>% 
  filter(!is.na(manip)) ->
  dat_rs

# Plots
limit <- max(abs(dat_rs$Percent_control), na.rm = TRUE) * c(-1, 1) + 100 
ggplot(dat_rs, aes(control, manip, color = Percent_control)) +
  geom_point(size = 4, na.rm = TRUE) + geom_abline() + 
  scale_color_distiller(palette = "BrBG", direction = 1, limit = limit, 
                        breaks = c(-200, 100, 400), labels = c(-200, 100, 400)) +
  facet_wrap(~depvar, scales = "free")

ggplot(dat_rs, aes(control, manip, color = Manipulation)) +
  geom_point(size = 3, na.rm = TRUE) + geom_abline() + 
  facet_wrap(~depvar, scales = "free")

ggplot(dat_rs, aes(manip / control, color = Manipulation)) + 
  geom_density(na.rm = TRUE) + facet_grid(depvar~., scales = "free")
```

# Metafor {.tabset}

```{r do_ma, message=FALSE}
library(metafor)
do_ma <- function(dat, condition, dv, output = TRUE) {
  dat %>% 
    filter(Manipulation == condition, depvar == dv) -> 
    dat_condition
  
  # Construct the meta-analysis variables and run the MA
  metadat <- escalc(measure = "SMD",
                    m1i = manip, m2i = control, 
                    sd1i = SD_manip, sd2i = SD_control,
                    n1i = N, n2i = N, 
                    slab = paste(Study_number, Author, Study_midyear),
                    data = dat_condition)
  
  # Arrange by response ratio
  metadat <- metadat[order(metadat$yi),]
  
  mam <- rma(yi, vi, data = metadat)
  
  if(output) {
    # Diagnostics
    print(summary(mam))
    forest.rma(mam)
    title(paste(condition, dv))
    plot(mam)
  }
  invisible(list(metadat = metadat, mam = mam))
}
```

## Irrigation

```{r irrigation}
do_ma(dat_rs, "Irrigation", "Rs_annual")
do_ma(dat_rs, "Irrigation", "Rh_annual")
do_ma(dat_rs, "Irrigation", "Rs_growingseason")
```

## Drought

```{r drought}
do_ma(dat_rs, "Drought", "Rs_annual")
do_ma(dat_rs, "Drought", "Rh_annual")
do_ma(dat_rs, "Drought", "Rs_growingseason")
```
